print("Tip Calculator")
bill=float(input("What was the total bill? \n"))
people = int(input("How many people to split the bill? \n"))
tip = int(input("How much tip would you like to give? 10,12 or 15? \n"))
bill = bill*(1+(tip/100))
finbill = "{:.2f}".format(bill/people)
print(f"Each person should pay : $ {finbill}")
